-- POSTGRES DATABASE INITIALIZE SCRIPT

-- Create USERS table
CREATE TABLE IF NOT EXISTS USERS (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USERNAME TEXT UNIQUE NOT NULL,
    PASSWORD_HASH TEXT NOT NULL,
    ROLE_ID INT NOT NULL DEFAULT 1,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    LAST_ACTIVE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- Create ROLES table
CREATE TABLE IF NOT EXISTS ROLES (
    ROLE_ID INT NOT NULL,
    ROLE_NAME TEXT NOT NULL,
    ROLE_DESCRIPTION TEXT NOT NULL
);

-- Insert BAN role to ROLES table
INSERT INTO TABLE ROLES (ROLE_ID, ROLE_NAME, ROLE_DESCRIPTION) VALUES (0, 'BAN', 'This role is for banned users');
-- Insert USER role to ROLES table
INSERT INTO TABLE ROLES (ROLE_ID, ROLE_NAME, ROLE_DESCRIPTION) VALUES (0, 'USER', 'This role is for regular users');
-- Insert ADMIN role to ROLES table
INSERT INTO TABLE ROLES (ROLE_ID, ROLE_NAME, ROLE_DESCRIPTION) VALUES (0, 'ADMIN', 'This role is for admin users');



