---------------------------------------------------------------------
-- POSTGRES DATABASE INITIALIZE SCRIPT
-- Author: Kenny Morris
-- Creation date: 01/02/2025
---------------------------------------------------------------------

-- Create USERS table
CREATE TABLE IF NOT EXISTS USERS (
    USER_ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USERNAME TEXT UNIQUE NOT NULL,
    EMAIL TEXT UNIQUE NOT NULL,
    PASSWORD_HASH TEXT NOT NULL,
    ROLE_ID INT NOT NULL DEFAULT 1,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    LAST_ACTIVE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- Create ROLES table
CREATE TABLE IF NOT EXISTS ROLES (
    ROLE_ID INT NOT NULL PRIMARY KEY,
    ROLE_NAME TEXT NOT NULL,
    ROLE_DESCRIPTION TEXT NOT NULL
);

-- Insert records into ROLES table
INSERT INTO ROLES (ROLE_ID, ROLE_NAME, ROLE_DESCRIPTION) VALUES (0, 'BAN', 'This role is for banned users') ON CONFLICT (ROLE_ID) DO NOTHING;
INSERT INTO ROLES (ROLE_ID, ROLE_NAME, ROLE_DESCRIPTION) VALUES (1, 'USER', 'This role is for regular users') ON CONFLICT (ROLE_ID) DO NOTHING;
INSERT INTO ROLES (ROLE_ID, ROLE_NAME, ROLE_DESCRIPTION) VALUES (2, 'ADMIN', 'This role is for admin users') ON CONFLICT (ROLE_ID) DO NOTHING;

